version: '3'

services:
  handbrake: 
    image: hydrohs/handbrake
    container_name: handbrake
    ports:
      - "2200:22"
      - "10000:10000"
    volumes:
      - ~/.ssh/authorized_keys:/authorized_keys:ro
      - config:/config
      - /storage:/storage
      - /output:/output
      - /watch:/watch
    env_file:
      - .env
    restart: unless-stopped

volumes:
  config:
