version: '3'

services:
  handbrake: 
    build: .
    ports:
      - "2201:22"
      - "10001:10000"
    volumes:
      - ~/.ssh/authorized_keys:/authorized_keys:ro
      - config:/config
      - /data/hydrohs:/storage
      - /data/hydrohs/ripped/complete:/output
      - /data/hydrohs/ripped/watch:/watch
    env_file:
      - .env
    restart: unless-stopped

volumes:
  config:
